/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("OperationObjectPageObjectPage journey");

        opaTest("Navigate to OperationObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheGenerated.onFilterBar().iExecuteSearch();

            Then.onTheGenerated.onTable().iCheckRows();
            When.onTheGenerated.onTable().iPressRow(0);

            Then.onTheOperationObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckAction("Ráállás elkezdése" /* , { enabled: true } */);
            // When.onTheOperationObjectPageGenerated.onHeader().iPressAction("Ráállás elkezdése");
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckAction("Ráállás befejezése" /* , { enabled: true } */);
            // When.onTheOperationObjectPageGenerated.onHeader().iPressAction("Ráállás befejezése");
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "Header1" });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header1",
                field: "SessionUserName",
                targetAnnotation: ""
            });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header1",
                field: "UserFullName",
                targetAnnotation: ""
            });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "Header2" });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header2",
                field: "SessionPersNumber",
                targetAnnotation: ""
            });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header2",
                field: "SessionEmpFullName",
                targetAnnotation: ""
            });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "Header3" });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header3",
                field: "SessionWorkCenterId",
                targetAnnotation: ""
            });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header3",
                field: "WorkCenterText",
                targetAnnotation: ""
            });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "Header4" });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header4",
                field: "SessionStartDateTime",
                targetAnnotation: ""
            });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header4",
                field: "WorkStart",
                targetAnnotation: ""
            });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header4",
                field: "WorkEnd",
                targetAnnotation: ""
            });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheOperationObjectPageGenerated.iCheckNumberOfSections(9);
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("AppNavigation");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "AppNavigation" });
            Then.onTheOperationObjectPageGenerated.onTable({ property: "_AppNav" }).iCheckColumns({"Title":{"header":"Alkalmazás"}});
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("OpHeader");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "OpHeader" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpHeader" }).iCheckField({ property: "ManufacturingOrder" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpHeader" }).iCheckField({ property: "ManufacturingOrderOperation" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpHeader" }).iCheckField({ property: "ProductDescription" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpHeader" }).iCheckField({ property: "Material" });
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("OpDetails");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "OpDetails" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpDetails" }).iCheckField({ property: "OperationDescription" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpDetails" }).iCheckField({ property: "OperationControlProfile" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpDetails" }).iCheckField({ property: "RelevantWorkCenterCode" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpDetails" }).iCheckField({ property: "WorkCenterID" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpDetails" }).iCheckField({ property: "Plant" });
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("Quantities");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "Quantities" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Quantities" }).iCheckField({ property: "OperationQuantity" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Quantities" }).iCheckField({ property: "ConfirmedYieldQty" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Quantities" }).iCheckField({ property: "ConfirmedScrapQty" });
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("Dates");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "Dates" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Dates" }).iCheckField({ property: "ErlstSchedldExecStrtTstmp" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Dates" }).iCheckField({ property: "ErlstSchedldExecEndTstmp" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Dates" }).iCheckField({ property: "SchedldDurationSeconds" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Dates" }).iCheckField({ property: "ActualExecutionStartTstmp" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Dates" }).iCheckField({ property: "ActualExecutionEndTstmp" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Dates" }).iCheckField({ property: "ActualDurationSeconds" });
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("StdValues");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "StdValues" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "StdValues" }).iCheckField({ property: "WorkCenterStandardWorkQty1" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "StdValues" }).iCheckField({ property: "WorkCenterStandardWorkQty2" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "StdValues" }).iCheckField({ property: "WorkCenterStandardWorkQty3" });
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("Status");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "Status" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Status" }).iCheckField({ property: "OperationIsMilestone" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Status" }).iCheckField({ property: "OperationIsReleased" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Status" }).iCheckField({ property: "OperationIsPartiallyConfirmed" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Status" }).iCheckField({ property: "OperationIsConfirmed" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Status" }).iCheckField({ property: "UserStatusShortText" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Status" }).iCheckField({ property: "UserStatusText" });
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("Components");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "Components" });
            Then.onTheOperationObjectPageGenerated.onTable({ property: "_Components" }).iCheckColumns({"CompId":{"header":"Item Text"},"Material":{"header":"Material"},"MatlCompRequirementDate":{"header":"Requirement Date"},"RequiredQuantity":{"header":"Requirement Quantity"},"WithdrawnQuantity":{"header":"Withdrawn Quantity"},"StorageLocation":{"header":"Storage Location"},"Batch":{"header":"Batch"},"ReservationIsFinallyIssued":{"header":"Final Issue"}});
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("Confirmations");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "Confirmations" });
            Then.onTheOperationObjectPageGenerated.onTable({ property: "_Confirmations" }).iCheckColumns({"ProductionOrder":{"header":"Production Order"},"ProductionOrderOperation":{"header":"Production Order Operation"},"ConfirmationOption":{"header":"Opció"},"PostingDate":{"header":"Posting Date"},"ConfirmationYieldQuantity":{"header":"Yield Quantity"},"ConfirmationScrapQuantity":{"header":"Scrap Quantity"},"ConfirmationText":{"header":"Confirmation Text"},"EnteredByUser":{"header":"Entered by User"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});